### ISSUE TITLE
mixed promise state when filtering using then()

### ISSUE THREAD

**Issue by thomheymann** [wookiehangover/underscore.deferred#17]
The library is mixing up promise states when filtering return values: 

``` javascript
var defer = $.Deferred(),
    filtered = defer.then( null, function( value ) {
        return value * 3;
    });

defer.reject( 6 );
filtered.fail(function( value ) {
    console.log( "Value is ( 3*6 = ) 18: " + value );
});
filtered.always(function( value ) {
    console.log( "State is: " + defer.state() );
    console.log( "Filtered State is: " + filtered.state() );
});
```

In browser using jQuery 1.8:

```
Value is ( 3*6 = ) 18: 18
State is: rejected
Filtered State is: rejected
```

In node using underscore.deferred:

```
State is: rejected
Filtered State is: resolved
```

I'm on 0.4.0 installed via npm

**Comment by wookiehangover** [comment]
This is expected behavior.

As specified, `.then` issues _another_ promise, rather than holding the reference to the original promise that it's chaining from. This is a breaking change from the jQuery implementation, and is [documented in the readme for 0.4.0](https://github.com/wookiehangover/underscore.deferred#_then). Take a look at [@domenic's explanation of this part of the promises A spec](https://gist.github.com/domenic/3889970) for the detailed reasoning behind this change.

Apologies for the confusion!
